import { useCallback, useEffect, useState } from 'react';
import { FiEdit2, FiVolume2, FiPlus, FiTrash2 } from 'react-icons/fi';
import Modal from '../../components/Modal';
import { EmptyState, ErrorState, LoadingState } from '../../components/AsyncState';
import AnnouncementForm from '../../components/forms/AnnouncementForm';
import { announcementService } from '../../services/announcements';
import { formatDate, getErrorMessage } from '../../utils/formatters';

export default function AdminAnnouncementsPage() {
  const [announcements, setAnnouncements] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editor, setEditor] = useState(null);
  const loadAnnouncements = useCallback(async () => { setLoading(true); setError(''); try { const response = await announcementService.list({ limit: 100 }); setAnnouncements(response.data.announcements); } catch (requestError) { setError(getErrorMessage(requestError)); } finally { setLoading(false); } }, []);
  useEffect(() => { loadAnnouncements(); }, [loadAnnouncements]);
  async function save(payload) { if (editor?.announcement) await announcementService.update(editor.announcement._id, payload); else await announcementService.create(payload); setEditor(null); await loadAnnouncements(); }
  async function remove(announcement) { if (!window.confirm(`Delete “${announcement.title}”?`)) return; try { await announcementService.remove(announcement._id); setAnnouncements((current) => current.filter((item) => item._id !== announcement._id)); } catch (requestError) { setError(getErrorMessage(requestError)); } }
  return <div><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">Official messaging</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Announcements</h2><p className="mt-2 text-slate-600">Publish clear updates that need everyone’s attention.</p></div><button className="button-primary" onClick={() => setEditor({ announcement: null })}><FiPlus /> New announcement</button></div>{loading ? <LoadingState label="Loading announcements..." /> : error ? <ErrorState message={error} onRetry={loadAnnouncements} /> : announcements.length ? <div className="space-y-3">{announcements.map((announcement) => <article className="surface p-5" key={announcement._id}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-teal-700"><FiVolume2 /><span className="text-sm font-semibold">{formatDate(announcement.createdAt)}</span></div><h3 className="mt-2 font-bold text-slate-900">{announcement.title}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-600">{announcement.content}</p></div><div className="flex gap-2"><button className="button-secondary !p-2.5" onClick={() => setEditor({ announcement })} aria-label="Edit announcement"><FiEdit2 /></button><button className="rounded-lg border border-rose-200 p-2.5 text-rose-700 hover:bg-rose-50" onClick={() => remove(announcement)} aria-label="Delete announcement"><FiTrash2 /></button></div></div></article>)}</div> : <EmptyState title="No announcements created" message="Share the first important community update." action={<button className="button-primary" onClick={() => setEditor({ announcement: null })}>New announcement</button>} />}{editor && <Modal title={editor.announcement ? 'Edit announcement' : 'New announcement'} onClose={() => setEditor(null)}><AnnouncementForm announcement={editor.announcement} onSubmit={save} onCancel={() => setEditor(null)} /></Modal>}</div>;
}
